#!/usr/bin/env bash
# =============================================================================
#  entrypoint.sh — container startup.
#
#  Prepares the runtime (ulimits, dirs, ngrok authtoken, optional auth, the
#  terminal welcome banner), then hands the process tree to supervisord, which
#  owns nginx, ttyd, ngrok, the Firebase URL writer and the keepalive.
# =============================================================================
set -euo pipefail

log() { printf '[entrypoint] %s\n' "$*"; }

# --- keep the process tree in the foreground, log everything -----------------
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export HOME="${HOME:-/root}"
export TERM="${TERM:-xterm-256color}"

# --- tunables (also read by supervisord.conf via %(ENV_...)s) ----------------
export NGINX_PORT="${NGINX_PORT:-8080}"
export TTYD_PORT="${TTYD_PORT:-7681}"
export TTYD_BASE_PATH="${TTYD_BASE_PATH:-/terminal}"
export NGROK_API="${NGROK_API:-http://127.0.0.1:4040/api/tunnels}"
export FIREBASE_DATABASE_URL="${FIREBASE_DATABASE_URL:-https://vps-server-2bcbd-default-rtdb.firebaseio.com}"
export FIREBASE_TUNNEL_PATH="${FIREBASE_TUNNEL_PATH:-/tunnel/url.json}"
export TUNNEL_POLL_INTERVAL="${TUNNEL_POLL_INTERVAL:-20}"
export TUNNEL_REFRESH_INTERVAL="${TUNNEL_REFRESH_INTERVAL:-600}"
export PORT_LIST="${PORT_LIST:-3000 4200 5173 8000 8080 8888}"

# NGROK_AUTHTOKEN may legitimately be empty (anonymous tunnel) — it only has to
# exist, because supervisord cannot expand an undefined %(ENV_)s variable.
export NGROK_AUTHTOKEN="${NGROK_AUTHTOKEN:-}"

# --- file descriptor limit ---------------------------------------------------
# Browsers open a lot of parallel connections: the terminal WebSocket, the page
# itself, and every asset the previewed app serves. The default 1024 is easy to
# exhaust once a Vite/webpack dev server is running.
if ! ulimit -n 65536 2>/dev/null; then
    log "WARNING: could not raise the open-file limit to 65536 (currently $(ulimit -n 2>/dev/null || echo unknown))"
else
    log "open-file limit: $(ulimit -n)"
fi

# --- runtime directories -----------------------------------------------------
mkdir -p /run /var/log/nginx /var/lib/nginx /var/www /etc/nginx/snippets \
         /root/.config/ngrok /root/.npm
rm -f /run/nginx.pid /run/supervisord.pid /run/supervisor.sock

# --- ngrok authtoken ---------------------------------------------------------
# The token lives in the deployment environment (Northflank runtime variables /
# secrets), never in the image.
if [ -n "${NGROK_AUTHTOKEN}" ]; then
    if ngrok config add-authtoken "${NGROK_AUTHTOKEN}" >/tmp/ngrok-authtoken.log 2>&1; then
        log "ngrok authtoken stored in ${HOME}/.config/ngrok/ngrok.yml"
    else
        log "WARNING: could not store the ngrok authtoken:"
        sed 's/^/            /' /tmp/ngrok-authtoken.log
    fi
    rm -f /tmp/ngrok-authtoken.log
else
    log "WARNING: NGROK_AUTHTOKEN is empty — the tunnel will be anonymous (expires after a few hours and shows an ngrok splash page)."
fi

# --- optional HTTP basic auth ------------------------------------------------
# Off by default: this is a public sandbox. Set TERMINAL_PASSWORD (and
# optionally TERMINAL_USER) and the terminal + port previews are gated while
# the landing page stays public so the platform health check keeps working.
: > /etc/nginx/snippets/optional-auth.conf
if [ -n "${TERMINAL_PASSWORD:-}" ]; then
    AUTH_USER="${TERMINAL_USER:-student}"
    htpasswd -bc /etc/nginx/htpasswd "${AUTH_USER}" "${TERMINAL_PASSWORD}" >/dev/null
    chmod 0644 /etc/nginx/htpasswd
    cat > /etc/nginx/snippets/optional-auth.conf <<'AUTH_SNIPPET'
        auth_basic           "Free Educational Coding Machine";
        auth_basic_user_file /etc/nginx/htpasswd;
AUTH_SNIPPET
    log "basic auth enabled for /terminal/ and /port/*/ (user: ${AUTH_USER})"
fi

# --- fail fast on a broken nginx config --------------------------------------
if ! nginx -t -c /etc/nginx/nginx.conf >/tmp/nginx-test.log 2>&1; then
    log "FATAL: nginx configuration test failed:"
    sed 's/^/        /' /tmp/nginx-test.log
    exit 1
fi
rm -f /tmp/nginx-test.log

# --- welcome banner for the web terminal -------------------------------------
# ttyd runs `bash -l`, so anything in /etc/profile.d runs on every new shell.
cat > /etc/profile.d/00-welcome.sh <<'WELCOME_EOF'
# Generated by entrypoint.sh — shown once per interactive login shell.
case "$-" in
    *i*) ;;
    *) return 0 2>/dev/null || exit 0 ;;
esac

CYAN='\033[38;5;110m'
DIM='\033[38;5;245m'
RESET='\033[0m'

printf "%b" "${CYAN}"
printf "  Free Educational Coding Machine\n"
printf "%b" "${DIM}"
printf "  sandboxed Linux · served entirely through one ngrok tunnel\n"
printf "%b" "${RESET}"
printf "\n"

if command -v node >/dev/null 2>&1; then
    printf "  node %s   npm %s   python %s\n" \
        "$(node -v 2>/dev/null)" "$(npm -v 2>/dev/null)" "$(python3 -V 2>/dev/null | awk '{print $2}')"
fi
printf "  %s\n" "git · nano · vim · htop · tmux · jq · ripgrep · curl · apt"
printf "\n"
printf "%b" "${DIM}"
printf "  install a coding agent : npm i -g @openai/codex   |   pip install aider-chat\n"
printf "  run something          : python3 -m http.server 8000   (then open it in Ports)\n"
printf "  preview a port         : /port/8000/ on this same URL, or the Ports panel in the UI\n"
printf "%b" "${RESET}"
printf "\n"
WELCOME_EOF
chmod 0644 /etc/profile.d/00-welcome.sh

log "nginx :${NGINX_PORT}   ttyd 127.0.0.1:${TTYD_PORT}${TTYD_BASE_PATH}   ngrok -> :${NGINX_PORT}"
log "preview ports: ${PORT_LIST} (any other port works too)"
log "starting supervisord"

# --- go -----------------------------------------------------------------------
# supervisord is PID 1: it restarts crashed children and forwards SIGTERM so a
# redeploy tears the whole tree down cleanly.
exec /usr/bin/supervisord --nodaemon --configuration /etc/supervisor/supervisord.conf
